import { selectors } from "../selectorDefinitions";
import { termsOfUse } from "../termsOfUse";
import { metadataTables } from '../metadataTables';

export const journeyTimeZoneTotalsDifference = {
  // pageName: "Journey Time Accessibility (Zone Totals) Difference",
  // url: "/accessibility-journey-time-totals-difference",
  // type: "MapLayout",
  // //termsOfUse: termsOfUse,
  // category: "Accessibility",
  // about: "", //To be added.
  // config: {
  //   layers: [
  //     {
  //       uniqueId: "NoRMSJourneyTimeAccessibilityTotalsDifference",
  //       name: "NoRMS Journey Time Accessibility Totals Difference",
  //       type: "tile",
  //       source: "api",
  //       path: "/api/vectortiles/zones/5/{z}/{x}/{y}", // matches the path in swagger.json
  //       sourceLayer: "zones",
  //       geometryType: "polygon",
  //       visualisationName: "Journey Time Accessibility Totals Difference",
  //       isHoverable: true,
  //       isStylable: true,
  //       shouldHaveTooltipOnClick: false,
  //       shouldHaveTooltipOnHover: true,
  //     },
  //   ],
  //   visualisations: [
  //     {
  //       name: "Journey Time Accessibility Totals Difference",
  //       type: "joinDataToMap",
  //       joinLayer: "NoRMS Journey Time Accessibility Totals Difference",
  //       style: "polygon-diverging",
  //       joinField: "id",
  //       valueField: "value",
  //       dataSource: "api",
  //       dataPath: "/api/norms/accessibility-journey-time-total/difference",
  //       legendText: [
  //         {
  //           legendSubtitleText: "mins" 
  //         }
  //       ]
  //     },
  //   ],
  //   metadataTables: [
  //     inputNormsScenarioMetadataTable,
  //     keyLocationTypeMetadataTable,
  //     userClassMetadataTable
  //   ],
  //   filters: [
  //     {
  //       filterName: "Filter Scenario 1 by Network",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "network_spec",
  //         paramColumn: "network_spec",
  //         sort: "ascending",
  //         exclude: ["NA"]
  //       },
  //     },
  //     {
  //       filterName: "Filter Scenario 1 by Demand Scenario",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "demand_code",
  //         paramColumn: "demand_code",
  //         sort: "ascending",
  //         exclude: ["NA"]
  //       },
  //     },
  //     {
  //       filterName: "Filter Scenario 1 by Year",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "scenario_year",
  //         paramColumn: "scenario_year",
  //         sort: "ascending",
  //         exclude: [0]
  //       },
  //     },
  //     {
  //       filterName: "Scenario 1",
  //       paramName: "scenarioCodeDoMinimum",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: false,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: false,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "scenario_code",
  //         paramColumn: "scenario_code",
  //         sort: "ascending",
  //         exclude: [0]
  //       },
  //     },
  //     {
  //       filterName: "Time Period - DM",
  //       paramName: "timePeriodCodesDoMinimum",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "toggle",
  //       shouldBeBlankOnInit: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: timePeriodCodesValues
  //     },
  //     {
  //       filterName: "Filter User Class by Segment - DM",
  //       paramName: "userClassIdsDoMinimum",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldBeValidated: false,
  //       shouldFilterOthers: true,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "user_segment",
  //         paramColumn: "user_segment",
  //         sort: "ascending",
  //         exclude: ['All']
  //       },
  //     },
      
  //     {
  //       filterName: "Filter User Class by Car Availability - DM",
  //       paramName: "userClassIdsDoMinimum",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: true,
  //       shouldBeValidated: false,
  //       shouldFilterOthers: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "car_availability",
  //         paramColumn: "car_availability",
  //         sort: "ascending",
  //         exclude: ['All']
  //       },
  //     },
  //     {
  //       filterName: "User Class - DM",
  //       paramName: "userClassIdsDoMinimum",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: true,
  //       shouldBeValidated: true,
  //       shouldFilterOthers: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "name",
  //         paramColumn: "id",
  //         sort: "ascending",
  //         exclude: [0, 123, 456, 789]
  //       },
  //     },
  //     {
  //       filterName: "Filter Scenario 2 by Network",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "network_spec",
  //         paramColumn: "network_spec",
  //         sort: "ascending",
  //         exclude: ["NA"]
  //       },
  //     },
  //     {
  //       filterName: "Filter Scenario 2 by Demand Scenario",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "demand_code",
  //         paramColumn: "demand_code",
  //         sort: "ascending",
  //         exclude: ["NA"]
  //       },
  //     },
  //     {
  //       filterName: "Filter Scenario 2 by Year",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: true,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "scenario_year",
  //         paramColumn: "scenario_year",
  //         sort: "ascending",
  //         exclude: [0]
  //       },
  //     },
  //     {
  //       filterName: "Scenario 2",
  //       paramName: "scenarioCodeDoSomething",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: false,
  //       shouldFilterOnValidation: false,
  //       shouldFilterOthers: false,
  //       multiSelect: false,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "input_norms_scenario",
  //         displayColumn: "scenario_code",
  //         paramColumn: "scenario_code",
  //         sort: "ascending",
  //         exclude: [0]
  //       },
  //     },
  //     {
  //       filterName: "Time Period - DS",
  //       paramName: "timePeriodCodesDoSomething",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "toggle",
  //       shouldBeBlankOnInit: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: timePeriodCodesValues
  //     },
  //     {
  //       filterName: "Filter User Class by Segment - DS",
  //       paramName: "userClassIdsDoSomething",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: false,
  //       shouldBeValidated: false,
  //       shouldFilterOthers: true,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "user_segment",
  //         paramColumn: "user_segment",
  //         sort: "ascending",
  //         exclude: ['All']
  //       },
  //     },
  //     {
  //       filterName: "Filter User Class by Car Availability - DS",
  //       paramName: "userClassIdsDoSomething",
  //       target: "validate",
  //       actions: [{ action: "none" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: true,
  //       shouldBeValidated: false,
  //       shouldFilterOthers: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "car_availability",
  //         paramColumn: "car_availability",
  //         sort: "ascending",
  //         exclude: ['All']
  //       },
  //     },
  //     {
  //       filterName: "User Class - DS",
  //       paramName: "userClassIdsDoSomething",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "dropdown",
  //       shouldBeBlankOnInit: true,
  //       shouldFilterOnValidation: true,
  //       shouldBeValidated: true,
  //       shouldFilterOthers: false,
  //       multiSelect: true,
  //       isClearable: true,
  //       values: {
  //         source: "metadataTable",
  //         metadataTableName: "norms_userclass_list",
  //         displayColumn: "name",
  //         paramColumn: "id",
  //         sort: "ascending",
  //         exclude: [0, 123, 456, 789]
  //       },
  //     },
  //     {
  //       filterName: "Origin Or Destination",
  //       paramName: "originOrDestination",
  //       target: "api",
  //       actions: [{ action: "UPDATE_QUERY_PARAMS" }],
  //       visualisations: ["Journey Time Accessibility Totals Difference"],
  //       type: "toggle",
  //       values: originOrDestinationValues
  //     }
  //   ]
  // }
}