name: Test and Publish to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  test_job:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'packages/vis-core/package-lock.json'

      - name: Install dependencies
        run: |
          cd packages/vis-core
          npm ci

      - name: Run tests
        run: |
          cd packages/vis-core
          npm test
        env:
          CI: true

  publish:
    needs: test_job
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@transport-for-the-north'

      - name: Install dependencies
        run: |
          cd packages/vis-core
          npm ci

      - name: Build package
        run: |
          cd packages/vis-core
          npm run build

      # vis-core-release-bot generates GitHub App Token to bypass push restrictions later
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Run semantic-release
        run: npx semantic-release
        working-directory: packages/vis-core
        env:
          # Uses the git token generated by the previous step for authentication to specifically bypass push restrictions
          # in order to merge back in the changes semantic-release makes to the package.json, package-lock.json, and CHANGELOG.md files.
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          # NODE_AUTH_TOKEN uses the default token for package registry authentication (then don't need additional permissions 
          # in the GitHub App -- important to minimise privileges)
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}